  - name: Check If maven is already installed or not
    shell: "mvn -version | grep -w 'Apache Maven' | awk '{print $3}'"
    register: maven_installed
    
  - name: Installed maven version
    debug: "msg={{maven_installed.stdout}}"
    
  - block:
    - name: Download and Unarchive maven
      unarchive:
        src: "https://dlcdn.apache.org/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz"
        dest: "/home/rahul/work"
        copy: no
        
    - name: Change ownership of maven directory
      file:
        path: /home/rahul/work/apache-maven-3.8.5
        owner: rahul
        group: rahul
        mode: "u+rwx,g+rx,o=rx"
        recurse: yes
        state: directory
                
    - name: Configure maven and its environment variables
      lineinfile:
        dest: "/home/rahul/work/maven.sh"
        line: "{{ item.line }}"
        create: yes
        state: present
        owner: rahul
        group: rahul
        mode: "u+rwx,g+rx,o=rx"
      with_items:
        - { line: 'export M2_HOME=/home/rahul/work/apache-maven-3.8.5' }
        - { line: 'export PATH=$PATH:$M2_HOME/bin' }
   
#    - name: Exports/Run maven env file for make M2_HOME available globally
#      command: "bash -c /home/rahul/work/maven.sh"
#      ". ./home/rahul/work/maven.sh"

    when: maven_installed.stdout == ""
